/*
 * Time_cfg.h
 *
 *  Created on: Sep 14, 2019
 *      Author: Na
 */

#ifndef TIME_CFG_H_
#define TIME_CFG_H_

/*******************************************************/

#define TIMER_u8T0_NORMAL_MOOD 0
#define TIMER_u8T0_PHASE_MOOD 1
#define TIMER_u8T0_FPWM_MOOD 2
#define TIMER_u8T0_PWM_MOOD 3

#define TIMER_u8T0_PRESCALE_X1 0
#define TIMER_u8T0_PRESCALE_X8 1
#define TIMER_u8T0_PRESCALE_X64 2
#define TIMER_u8T0_PRESCALE_X256 3
#define TIMER_u8T0_PRESCALE_X1024 4

#define TIMER_u8T0_FPWM_NRML 0
#define TIMER_u8T0_FPWM_CLRCMP_STTP 1
#define TIMER_u8T0_FPWM_STCMP_CLRTP 2


#define TIMER_u8T1_NORMAL_MOOD 0
#define TIMER_u8T1_PHASE_MOOD 1
#define TIMER_u8T1_FPWM_MOOD 2
#define TIMER_u8T1_PWM_MOOD 3

#define TIMER_u8T1_PRESCALE_X1 0
#define TIMER_u8T1_PRESCALE_X8 1
#define TIMER_u8T1_PRESCALE_X64 2
#define TIMER_u8T1_PRESCALE_X256 3
#define TIMER_u8T1_PRESCALE_X1024 4

#define TIMER_u8T1_FPWM_NRML 0
#define TIMER_u8T1_FPWM_CLRCMP_STTP 1
#define TIMER_u8T1_FPWM_STCMP_CLRTP 2



#define TIMER_u8T2_NORMAL_MOOD 0
#define TIMER_u8T2_PHASE_MOOD 1
#define TIMER_u8T2_FPWM_MOOD 2
#define TIMER_u8T2_PWM_MOOD 3

#define TIMER_u8T2_PRESCALE_X1 0
#define TIMER_u8T2_PRESCALE_X8 1
#define TIMER_u8T2_PRESCALE_X64 2
#define TIMER_u8T2_PRESCALE_X256 3
#define TIMER_u8T2_PRESCALE_X1024 4

#define TIMER_u8T2_FPWM_NRML 0
#define TIMER_u8T2_FPWM_CLRCMP_STTP 1
#define TIMER_u8T2_FPWM_STCMP_CLRTP 2

/*************************config options**************************/

#define TIMER_u8T0_MOOD TIMER_u8T0_FPWM_MOOD
#define TIMER_u8T0_PRESCALE TIMER_u8T0_PRESCALE_X1
#define TIMER_u8T0_FPWM_MOOD_TYPE TIMER_u8T0_FPWM_CLRCMP_STTP

#define TIMER_u8T1_MOOD TIMER_u8T1_FPWM_MOOD
#define TIMER_u8T1_PRESCALE TIMER_u8T1_PRESCALE_X1
#define TIMER_u8T1_FPWM_MOOD_TYPE TIMER_u8T0_FPWM_CLRCMP_STTP

#define TIMER_u8T2_MOOD TIMER_u8T2_FPWM_MOOD
#define TIMER_u8T2_PRESCALE TIMER_u8T2_PRESCALE_X1
#define TIMER_u8T2_FPWM_MOOD_TYPE TIMER_u8T2_FPWM_CLRCMP_STTP

#endif /* TIME_CFG_H_ */
