/*
 * Timer_prg.c
 *
 *  Created on: Sep 14, 2019
 *      Author: Na
 */

#include "Std_types.h"
#include "Bit_math.h"

#include <avr/io.h>

#include "Time_cfg.h"
#include "Timer_int.h"


void Timer_vidInit(u8 ID)
{
	if(ID ==Timer_u8Timer_0)
	{
#if TIMER_u8T0_MOOD==TIMER_u8T0_NORMAL_MOOD

#elif TIMER_u8T0_MOOD==TIMER_u8T0_PHASE_MOOD

#elif TIMER_u8T0_MOOD==TIMER_u8T0_PWM_MOOD


#elif TIMER_u8T0_MOOD==TIMER_u8T0_FPWM_MOOD
		SET_BIT(TCCR0,6);
		SET_BIT(TCCR0,3);

#endif

#if TIMER_u8T0_FPWM_MOOD_TYPE==TIMER_u8T0_FPWM_NRML
		CLEAR_BIT(TCCR0,5);
		CLEAR_BIT(TCCR0,4);
#elif TIMER_u8T0_FPWM_MOOD_TYPE==TIMER_u8T0_FPWM_CLRCMP_STTP
		SET_BIT(TCCR0,5);
		CLEAR_BIT(TCCR0,4);

#elif TIMER_u8T0_FPWM_MOOD_TYPE==TIMER_u8T0_FPWM_STCMP_CLRTP
		SET_BIT(TCCR0,5);
		SET_BIT(TCCR0,4);
#endif

#if TIMER_u8T0_PRESCALE==TIMER_u8T0_PRESCALE_X1
		CLEAR_BIT(TCCR0,2);
		CLEAR_BIT(TCCR0,1);
		SET_BIT(TCCR0,0);
#elif TIMER_u8T0_PRESCALE==TIMER_u8T0_PRESCALE_X8
		CLEAR_BIT(TCCR0,2);
		CLEAR_BIT(TCCR0,1);
		SET_BIT(TCCR0,0);
#elif TIMER_u8T0_PRESCALE==TIMER_u8T0_PRESCALE_X64
		CLEAR_BIT(TCCR0,2);
		CLEAR_BIT(TCCR0,1);
		SET_BIT(TCCR0,0);
#elif TIMER_u8T0_PRESCALE==TIMER_u8T0_PRESCALE_X256
		CLEAR_BIT(TCCR0,2);
		CLEAR_BIT(TCCR0,1);
		SET_BIT(TCCR0,0);
#elif TIMER_u8T0_PRESCALE==TIMER_u8T0_PRESCALE_X1024
		CLEAR_BIT(TCCR0,2);
		CLEAR_BIT(TCCR0,1);
		SET_BIT(TCCR0,0);
#endif


	}
	else if(ID ==Timer_u8Timer_1)
	{
		SET_BIT(TCCR1A,7);
		CLEAR_BIT(TCCR1A,6);

	}
	else if(ID ==Timer_u8Timer_2)
	{
#if TIMER_u8T1_MOOD==TIMER_u8T1_NORMAL_MOOD

#elif TIMER_u8T1_MOOD==TIMER_u8T1_PHASE_MOOD

#elif TIMER_u8T1_MOOD==TIMER_u8T1_PWM_MOOD


#elif TIMER_u8T1_MOOD==TIMER_u8T1_FPWM_MOOD
		SET_BIT(TCCR0,6);
		SET_BIT(TCCR0,3);

#endif

#if TIMER_u8T1_FPWM_MOOD_TYPE==TIMER_u8T1_FPWM_NRML
		CLEAR_BIT(TCCR0,5);
		CLEAR_BIT(TCCR0,4);
#elif TIMER_u8T1_FPWM_MOOD_TYPE==TIMER_u8T1_FPWM_CLRCMP_STTP
		SET_BIT(TCCR0,5);
		CLEAR_BIT(TCCR0,4);

#elif TIMER_u8T1_FPWM_MOOD_TYPE==TIMER_u8T1_FPWM_STCMP_CLRTP
		SET_BIT(TCCR0,5);
		SET_BIT(TCCR0,4);
#endif

#if TIMER_u8T1_PRESCALE==TIMER_u8T1_PRESCALE_X1
		CLEAR_BIT(TCCR0,2);
		CLEAR_BIT(TCCR0,1);
		SET_BIT(TCCR0,0);
#elif TIMER_u8T1_PRESCALE==TIMER_u8T1_PRESCALE_X8
		CLEAR_BIT(TCCR0,2);
		CLEAR_BIT(TCCR0,1);
		SET_BIT(TCCR0,0);
#elif TIMER_u8T1_PRESCALE==TIMER_u8T1_PRESCALE_X64
		CLEAR_BIT(TCCR0,2);
		CLEAR_BIT(TCCR0,1);
		SET_BIT(TCCR0,0);
#elif TIMER_u8T1_PRESCALE==TIMER_u8T1_PRESCALE_X256
		CLEAR_BIT(TCCR0,2);
		CLEAR_BIT(TCCR0,1);
		SET_BIT(TCCR0,0);
#elif TIMER_u8T1_PRESCALE==TIMER_u8T1_PRESCALE_X1024
		CLEAR_BIT(TCCR0,2);
		CLEAR_BIT(TCCR0,1);
		SET_BIT(TCCR0,0);
#endif



	}


}
